### ISSUE TITLE
Blown Out Raw Highlights Replaces with Boxes in LZ 4.2

### ISSUE THREAD

**Issue by sfink16** [AntonKast/LightZone#11]
Apparently it is in any raw image as confirmed by Jacal as seen in [THIS THREAD](http://lightzoneproject.org/lorum/boxes-canon-5d-mkiv-raw-images).  

It only happens with the new version 4.2.0, apparently with any raw photo, containing blown-out highlights (tested with another Canon and an old Pentax). The  saved _lzn files are broken, but when converted/exported to tiff or jpeg, the artefacts are gone.

Checked with LightZone 4.1.9 and 4.2.0 on a Windows 10 laptop.  

Personally, when I tried to convert to Tiff LZ 4.2 crashed.  Plus I still see the boxes when converting to JPG.

Steve

**Comment by ktgw0316** [comment]
@sfink16: I've just migrated this to actively maintained repository (https://github.com/Aries85/LightZone/issues/247) and closed the issue there.

I don't have permission on this repository (AntonKast/LightZone), so could you please close this issue by yourself?

**Comment by sfink16** [comment]
Thanks!
